// <auto-generated by="the Blazor I18n Text compiler" />
namespace InterfazUsuario.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About"</summary>
        public string About;

        /// <summary>"Balance"</summary>
        public string Balance;

        /// <summary>"Business Name"</summary>
        public string BusinessName;

        /// <summary>"Calendar"</summary>
        public string Calendar;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Client"</summary>
        public string Cliente;

        /// <summary>"Clients"</summary>
        public string Clients;

        /// <summary>"Counter"</summary>
        public string Counter;

        /// <summary>"Create Event"</summary>
        public string CreateEvent;

        /// <summary>"CUIT"</summary>
        public string CUIT;

        /// <summary>"Date"</summary>
        public string Date;

        /// <summary>"DateTime"</summary>
        public string DateTime;

        /// <summary>"Delete"</summary>
        public string Delete;

        /// <summary>"Description"</summary>
        public string Description;

        /// <summary>"DNI"</summary>
        public string DNI;

        /// <summary>"Email"</summary>
        public string Email;

        /// <summary>"Event"</summary>
        public string Event;

        /// <summary>"Event Name"</summary>
        public string EventName;

        /// <summary>"Events"</summary>
        public string Events;

        /// <summary>"Event Type"</summary>
        public string EventType;

        /// <summary>"Export"</summary>
        public string Export;

        /// <summary>"Fetch Data"</summary>
        public string Fetchdata;

        /// <summary>"From Date"</summary>
        public string FromDate;

        /// <summary>"Guest"</summary>
        public string Guest;

        /// <summary>"Guests"</summary>
        public string Guests;

        /// <summary>"Hello World!"</summary>
        public string Hello_World;

        /// <summary>"Home"</summary>
        public string Home;

        /// <summary>"Log"</summary>
        public string Log;

        /// <summary>"Login"</summary>
        public string Login;

        /// <summary>"Logout"</summary>
        public string Logout;

        /// <summary>"MercadoPago"</summary>
        public string MercadoPago;

        /// <summary>"Message"</summary>
        public string Message;

        /// <summary>"Messages"</summary>
        public string Messages;

        /// <summary>"My Event"</summary>
        public string MyEvent;

        /// <summary>"Name"</summary>
        public string Name;

        /// <summary>"Save"</summary>
        public string Save;

        /// <summary>"Send Email"</summary>
        public string SendEmail;

        /// <summary>"Severity"</summary>
        public string Severity;

        /// <summary>"Surname"</summary>
        public string Surname;

        /// <summary>"To Date"</summary>
        public string ToDate;

        /// <summary>"Update"</summary>
        public string Update;

        /// <summary>"User"</summary>
        public string User;
    }
}
